### ISSUE TITLE
Accessibility fixes to port over from Wātea

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/bambusa-theme#30]
Bring over the accessibility improvements currently going into Wātea to Bambusa (select ones which are most relevant).
To be ported over once functionality is added:

  - [x] silverstripe/cwp-watea-theme#96 (Language selector)
  - [x] silverstripe/cwp-watea-theme#97 (Search)
  - [x] silverstripe/cwp-watea-theme#92 (Indicators)
  - [x] silverstripe/cwp-watea-theme#99 (Colour picker work)

**Comment by sachajudd** [comment]
I'm pretty sure I've ported all of these over in this commit @clarkepaul  https://github.com/silverstripe/bambusa-theme/pull/22
